#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
MASTER ORCHESTRATOR: HEMATITE E2E WORKFLOW
==========================================

Description:
    Main execution script for the Hematite(001)-Water-Arsenate simulation.
    It orchestrates the modular Python builders, Packmol solvation, and
    LAMMPS simulation stages.

    It treats all steps as distinct, ensuring robust error handling.

Workflow Sequence:
    1. Build Geometry Components (python build_system_E2E.py)
    2. Run Solvation             (packmol < packmol.inp)
    3. Convert to LAMMPS         (python convert_to_lammps.py)
    4. Minimization              (LAMMPS -> in.minimize)
    5. Heating                   (LAMMPS -> in.heat)
    6. Sanitization              (python sanitize_data.py)
    7. Production                (LAMMPS -> in.production)
    8. Analysis                  (python plot_results.py)

Date: February 2026
Version: 3.1 (Repository Release - With Explicit Solvation)
"""

import os
import sys
import time
import subprocess
from datetime import datetime

# =============================================================================
# CONFIGURATION
# =============================================================================

# Executable Commands (Adjust to your system aliases)
LAMMPS_CMD = "mpirun -np 4 lmp"
PACKMOL_CMD = "packmol"
PYTHON_CMD = "python3"

# Required Input Files (Must exist before starting)
REQUIRED_INPUTS = [
    "Hematita.cif",
    "build_system_E2E.py",
    "convert_to_lammps.py",
    "sanitize_data.py",
    "plot_results.py",
    "in.minimize",
    "in.heat",
    "in.production"
]

# Log File
LOG_FILE = "workflow_execution.log"

# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def log(message, to_file=True):
    """Prints message to console and writes to log."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formatted_msg = f"[{timestamp}] {message}"
    print(formatted_msg)
    if to_file:
        with open(LOG_FILE, "a") as f:
            f.write(formatted_msg + "\n")

def check_prerequisites():
    """Verifies existence of scripts and input files."""
    log("Checking prerequisites...")
    missing = []
    for filename in REQUIRED_INPUTS:
        if not os.path.exists(filename):
            missing.append(filename)

    # Check executables (basic check)
    if shutil.which(PACKMOL_CMD.split()[0]) is None:
        log(f"WARNING: '{PACKMOL_CMD}' executable not found in PATH.")

    if missing:
        log(f"CRITICAL ERROR: Missing required files: {missing}")
        sys.exit(1)
    log("All prerequisites found.")

def run_step(command, step_name, output_file=None):
    """
    Executes a shell command.
    If output_file is provided (e.g., for Packmol redirection), handles it.
    """
    log(f"--- STARTING STEP: {step_name} ---")
    log(f"Command: {command}")

    start_time = time.time()

    try:
        # Special handling for redirection like "packmol < packmol.inp"
        # Since subprocess.run with shell=True handles redirection naturally on Linux/Mac,
        # we stick to simple string commands.
        subprocess.run(command, shell=True, check=True)

    except subprocess.CalledProcessError as e:
        log(f"!!! FAILURE in step: {step_name} !!!")
        log(f"Return Code: {e.returncode}")
        sys.exit(e.returncode)

    elapsed = time.time() - start_time
    log(f"--- FINISHED STEP: {step_name} (Duration: {elapsed:.2f}s) ---\n")

import shutil # Needed for check_prerequisites

# =============================================================================
# MAIN PIPELINE
# =============================================================================

def main():
    # Initialize Log
    with open(LOG_FILE, "w") as f:
        f.write(f"WORKFLOW EXECUTION LOG - {datetime.now()}\n")
        f.write("=========================================\n\n")

    print("""
    ######################################################
       HEMATITE E2E WORKFLOW - MASTER ORCHESTRATOR
    ######################################################
    """)

    # 1. Check Environment
    check_prerequisites()

    # 2. Build Geometry Components
    # Generates: hematite_slab.pdb, water.pdb, arsenate.pdb, AND packmol.inp
    run_step(f"{PYTHON_CMD} build_system_E2E.py", "Geometry Generation")

    # 3. Run Solvation (Packmol)
    # Generates: system_solvated.pdb
    # Note: We assume build_system_E2E.py created 'packmol.inp'
    if not os.path.exists("packmol.inp"):
        log("ERROR: packmol.inp was not generated by the previous step.")
        sys.exit(1)

    run_step(f"{PACKMOL_CMD} < packmol.inp", "Packmol Solvation")

    # 4. Convert to LAMMPS Topology
    # Generates: system.data
    run_step(f"{PYTHON_CMD} convert_to_lammps.py", "LAMMPS Conversion")

    # 5. Minimization
    # Generates: system_minimized.data
    run_step(f"{LAMMPS_CMD} -in in.minimize", "LAMMPS Minimization")

    # 6. Heating
    # Generates: system_heated.data
    run_step(f"{LAMMPS_CMD} -in in.heat", "LAMMPS Heating")

    # 7. Sanitization (Prepare Slab Boundary)
    # Generates: system_fixed.data
    run_step(f"{PYTHON_CMD} sanitize_data.py", "Coordinate Sanitization")

    # 8. Production Run
    # Generates: system_final.data, density_profile.profile
    run_step(f"{LAMMPS_CMD} -in in.production", "LAMMPS Production")

    # 9. Analysis
    # Generates: Plots
    run_step(f"{PYTHON_CMD} plot_results.py", "Data Analysis")

    log("======================================================")
    log("   WORKFLOW COMPLETED SUCCESSFULLY")
    log("======================================================")

if __name__ == "__main__":
    main()
